spring:
  profiles:
    active: dev

#kafka integration
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: bet.BuildUI.NotificationService # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


#  mongodb config for subscriber database
  data:
    mongodb:
      uri: mongodb+srv://dhiraj_123:i2R517lUNn1CPBSa@cluster0.15zztmy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: subscriberdb
      auto-index-creation : true